services:
  rp:
    build: .
    container_name: rp_dev
    volumes:
      - ./dev:/shared  # Mount everything in shared folder
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    stdin_open: true   # Allows interactive shell
    tty: true          # Enables interactive mode