/*This file was generated by NativeWind. Do not edit!*/
const { NativeWindStyleSheet: _NativeWindStyleSheet } = require('nativewind');
_NativeWindStyleSheet.create({
  styles: {
    '*': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    '': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    html: {
      lineHeight: 1.5,
      fontFamily: 'ui-sans-serif',
    },
    body: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    hr: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    'abbr:where([title])': {
      textDecorationLine: 'underline',
      textDecorationColor: 'black',
      textDecorationStyle: 'dotted',
    },
    code: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    kbd: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    samp: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    pre: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    small: {
      fontSize: '80%',
    },
    sub: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    sup: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    button: {
      backgroundColor: 'transparent',
    },
    input: {
      opacity: 1,
      color: '#9ca3af',
    },
    optgroup: {
      fontFamily: 'inherit',
      fontSize: '100%',
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    select: {
      textTransform: 'none',
    },
    textarea: {
      opacity: 1,
      color: '#9ca3af',
    },
    "[type='button']": {
      backgroundColor: 'transparent',
    },
    "[type='reset']": {
      backgroundColor: 'transparent',
    },
    "[type='submit']": {
      backgroundColor: 'transparent',
    },
    ':-moz-ui-invalid': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'black',
      shadowOpacity: 1,
    },
    blockquote: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dl: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dd: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h1: {
      fontFamily: 'RacingSansOne',
      fontSize: 30,
      letterSpacing: '0.025em',
    },
    h2: {
      fontFamily: 'RacingSansOne',
      fontSize: 24,
      letterSpacing: '0.025em',
    },
    h3: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h4: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h5: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h6: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    figure: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    p: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    fieldset: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    legend: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ol: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ul: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    menu: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    img: {
      maxWidth: '100%',
    },
    video: {
      maxWidth: '100%',
    },
    '[hidden]': {
      display: 'none',
    },
    'font-racing': {
      fontFamily: 'RacingSansOne',
    },
    'font-inter': {
      fontFamily: 'Inter',
    },
    container: {
      width: '100%',
    },
    'container@0': {
      maxWidth: 640,
    },
    'container@1': {
      maxWidth: 768,
    },
    'container@2': {
      maxWidth: 1024,
    },
    'container@3': {
      maxWidth: 1280,
    },
    'container@4': {
      maxWidth: 1536,
    },
    'body-bold': {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '700',
    },
    card: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomLeftRadius: 24,
      backgroundColor: 'rgb(255, 255, 255)',
      paddingTop: 32,
      paddingRight: 32,
      paddingBottom: 32,
      paddingLeft: 32,
    },
    'tab-icon': {
      alignItems: 'center',
      justifyContent: 'center',
      borderTopLeftRadius: 9999,
      borderTopRightRadius: 9999,
      borderBottomRightRadius: 9999,
      borderBottomLeftRadius: 9999,
      backgroundColor: 'rgba(31, 41, 55, 1)',
      width: 40,
      height: 40,
    },
    'tab-icon-active': {
      backgroundColor: 'rgba(37, 99, 235, 1)',
    },
    absolute: {
      position: 'absolute',
    },
    relative: {
      position: 'relative',
    },
    'inset-x-0': {
      left: 0,
      right: 0,
    },
    'bottom-0': {
      bottom: 0,
    },
    'bottom-[2%]': {
      bottom: '2%',
    },
    'left-0': {
      left: 0,
    },
    'right-0': {
      right: 0,
    },
    'right-[10%]': {
      right: '10%',
    },
    'top-0': {
      top: 0,
    },
    'top-[50%]': {
      top: '50%',
    },
    'z-0': {
      zIndex: 0,
    },
    'z-10': {
      zIndex: 10,
    },
    'z-20': {
      zIndex: 20,
    },
    'mx-auto': {
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    'mt-0': {
      marginTop: 0,
    },
    'mt-[-30px]': {
      marginTop: -30,
    },
    'mt-[-5px]': {
      marginTop: -5,
    },
    flex: {
      display: 'flex',
    },
    hidden: {
      display: 'none',
    },
    'h-0': {
      height: 0,
    },
    'h-[30px]': {
      height: 30,
    },
    'h-[4px]': {
      height: 4,
    },
    'h-[50%]': {
      height: '50%',
    },
    'h-[52px]': {
      height: 52,
    },
    'h-[60%]': {
      height: '60%',
    },
    'h-[70px]': {
      height: 70,
    },
    'h-[75px]': {
      height: 75,
    },
    'h-[80%]': {
      height: '80%',
    },
    'h-full': {
      height: '100%',
    },
    'h-px': {
      height: 1,
    },
    'w-4/5': {
      width: '80%',
    },
    'w-[16%]': {
      width: '16%',
    },
    'w-[30px]': {
      width: 30,
    },
    'w-[80%]': {
      width: '80%',
    },
    'w-[85%]': {
      width: '85%',
    },
    'w-full': {
      width: '100%',
    },
    'min-w-[250px]': {
      minWidth: 250,
    },
    'max-w-[340px]': {
      maxWidth: 340,
    },
    'flex-1': {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: '0%',
    },
    'flex-row': {
      flexDirection: 'row',
    },
    'items-end': {
      alignItems: 'flex-end',
    },
    'items-center': {
      alignItems: 'center',
    },
    'justify-end': {
      justifyContent: 'flex-end',
    },
    'justify-center': {
      justifyContent: 'center',
    },
    'justify-between': {
      justifyContent: 'space-between',
    },
    'justify-evenly': {
      justifyContent: 'space-evenly',
    },
    'self-end': {
      alignSelf: 'flex-end',
    },
    'self-center': {
      alignSelf: 'center',
    },
    'self-stretch': {
      alignSelf: 'stretch',
    },
    'overflow-hidden': {
      overflow: 'hidden',
    },
    truncate: {
      overflow: 'hidden',
    },
    rounded: {
      borderTopLeftRadius: '0.25rem',
      borderTopRightRadius: '0.25rem',
      borderBottomRightRadius: '0.25rem',
      borderBottomLeftRadius: '0.25rem',
    },
    'rounded-2xl': {
      borderTopLeftRadius: '1rem',
      borderTopRightRadius: '1rem',
      borderBottomRightRadius: '1rem',
      borderBottomLeftRadius: '1rem',
    },
    'rounded-full': {
      borderTopLeftRadius: 9999,
      borderTopRightRadius: 9999,
      borderBottomRightRadius: 9999,
      borderBottomLeftRadius: 9999,
    },
    'rounded-lg': {
      borderTopLeftRadius: '0.5rem',
      borderTopRightRadius: '0.5rem',
      borderBottomRightRadius: '0.5rem',
      borderBottomLeftRadius: '0.5rem',
    },
    'rounded-md': {
      borderTopLeftRadius: '0.375rem',
      borderTopRightRadius: '0.375rem',
      borderBottomRightRadius: '0.375rem',
      borderBottomLeftRadius: '0.375rem',
    },
    'rounded-sm': {
      borderTopLeftRadius: '0.125rem',
      borderTopRightRadius: '0.125rem',
      borderBottomRightRadius: '0.125rem',
      borderBottomLeftRadius: '0.125rem',
    },
    'rounded-xl': {
      borderTopLeftRadius: '0.75rem',
      borderTopRightRadius: '0.75rem',
      borderBottomRightRadius: '0.75rem',
      borderBottomLeftRadius: '0.75rem',
    },
    border: {
      borderTopWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
    },
    'border-gray-300': {
      borderTopColor: 'rgba(209, 213, 219, 1)',
      borderRightColor: 'rgba(209, 213, 219, 1)',
      borderBottomColor: 'rgba(209, 213, 219, 1)',
      borderLeftColor: 'rgba(209, 213, 219, 1)',
    },
    'bg-[#00adb5]': {
      backgroundColor: 'rgba(0, 173, 181, 1)',
    },
    'bg-[#222]': {
      backgroundColor: 'rgba(34, 34, 34, 1)',
    },
    'bg-[#333333]': {
      backgroundColor: 'rgba(51, 51, 51, 1)',
    },
    'bg-[#333]': {
      backgroundColor: 'rgba(51, 51, 51, 1)',
    },
    'bg-[#555]': {
      backgroundColor: 'rgba(85, 85, 85, 1)',
    },
    'bg-[#A3A3A3FF]': {
      backgroundColor: '#A3A3A3FF',
    },
    'bg-[#CA2523]': {
      backgroundColor: 'rgba(202, 37, 35, 1)',
    },
    'bg-[#D9D9D9]': {
      backgroundColor: 'rgba(217, 217, 217, 1)',
    },
    'bg-[#EEEEEE]': {
      backgroundColor: 'rgba(238, 238, 238, 1)',
    },
    'bg-[#F0363D]': {
      backgroundColor: 'rgba(240, 54, 61, 1)',
    },
    'bg-[#ccc]': {
      backgroundColor: 'rgba(204, 204, 204, 1)',
    },
    'bg-[#dbdbdb]': {
      backgroundColor: 'rgba(219, 219, 219, 1)',
    },
    'bg-black': {
      backgroundColor: 'rgba(0, 0, 0, 1)',
    },
    'bg-black/40': {
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    'bg-black/50': {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    'bg-black/60': {
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    'bg-gray-200': {
      backgroundColor: 'rgba(229, 231, 235, 1)',
    },
    'bg-gray-300': {
      backgroundColor: 'rgba(209, 213, 219, 1)',
    },
    'bg-gray-500': {
      backgroundColor: 'rgba(107, 114, 128, 1)',
    },
    'bg-white': {
      backgroundColor: 'rgba(255, 255, 255, 1)',
    },
    'text-left': {
      textAlign: 'left',
    },
    'text-center': {
      textAlign: 'center',
    },
    'font-magistral': {
      fontFamily: 'Magistral',
    },
    'font-magistralMedium': {
      fontFamily: 'MagistralMedium',
    },
    'font-proRacing': {
      fontFamily: 'ProRacing',
    },
    'font-proRacingSlant': {
      fontFamily: 'ProRacingSlant',
    },
    'text-2xl': {
      fontSize: '1.5rem',
      lineHeight: '2rem',
    },
    'text-3xl': {
      fontSize: '1.875rem',
      lineHeight: '2.25rem',
    },
    'text-4xl': {
      fontSize: '2.25rem',
      lineHeight: '2.5rem',
    },
    'text-[10px]': {
      fontSize: 10,
    },
    'text-[12px]': {
      fontSize: 12,
    },
    'text-[14px]': {
      fontSize: 14,
    },
    'text-[16px]': {
      fontSize: 16,
    },
    'text-[18px]': {
      fontSize: 18,
    },
    'text-[22px]': {
      fontSize: 22,
    },
    'text-[24px]': {
      fontSize: 24,
    },
    'text-[30px]': {
      fontSize: 30,
    },
    'text-[32px]': {
      fontSize: 32,
    },
    'text-[40px]': {
      fontSize: 40,
    },
    'text-base': {
      fontSize: '1rem',
      lineHeight: '1.5rem',
    },
    'text-lg': {
      fontSize: '1.125rem',
      lineHeight: '1.75rem',
    },
    'text-sm': {
      fontSize: '0.875rem',
      lineHeight: '1.25rem',
    },
    'text-xl': {
      fontSize: '1.25rem',
      lineHeight: '1.75rem',
    },
    'text-xs': {
      fontSize: '0.75rem',
      lineHeight: '1rem',
    },
    'font-bold': {
      fontWeight: '700',
    },
    'font-extrabold': {
      fontWeight: '800',
    },
    'font-normal': {
      fontWeight: '400',
    },
    'font-semibold': {
      fontWeight: '600',
    },
    italic: {
      fontStyle: 'italic',
    },
    'not-italic': {
      fontStyle: 'normal',
    },
    'leading-5': {
      lineHeight: '1.25rem',
    },
    'leading-[14px]': {
      lineHeight: 14,
    },
    'tracking-[2px]': {
      letterSpacing: 2,
    },
    'tracking-wide': {
      letterSpacing: '0.025em',
    },
    'tracking-wider': {
      letterSpacing: '0.05em',
    },
    'text-[#00adb5]': {
      color: 'rgba(0, 173, 181, 1)',
    },
    'text-[#666]': {
      color: 'rgba(102, 102, 102, 1)',
    },
    'text-[#B60000]': {
      color: 'rgba(182, 0, 0, 1)',
    },
    'text-[#CA2523]': {
      color: 'rgba(202, 37, 35, 1)',
    },
    'text-[#F0363D]': {
      color: 'rgba(240, 54, 61, 1)',
    },
    'text-[#FFFFFF]': {
      color: 'rgba(255, 255, 255, 1)',
    },
    'text-black': {
      color: 'rgba(0, 0, 0, 1)',
    },
    'text-gray-500': {
      color: 'rgba(107, 114, 128, 1)',
    },
    'text-green-500': {
      color: 'rgba(34, 197, 94, 1)',
    },
    'text-white': {
      color: 'rgba(255, 255, 255, 1)',
    },
    underline: {
      textDecorationLine: 'underline',
    },
    'opacity-80': {
      opacity: 0.8,
    },
  },
  atRules: {
    container: [
      [['media', '(min-width: 640px)']],
      [['media', '(min-width: 768px)']],
      [['media', '(min-width: 1024px)']],
      [['media', '(min-width: 1280px)']],
      [['media', '(min-width: 1536px)']],
    ],
  },
  topics: {
    container: ['width'],
  },
});
