import type { Event } from '@/api/types';

// Temporary display data for the mobile schedule. Remove this list and its use
// in app/(tabs)/events.tsx once real events are available from the API.
export const TEMPORARY_EVENTS: Event[] = [
  {
    eventId: 'temporary-2025-attendee-check-in',
    name: 'Attendee Check-In',
    startTime: '2025-09-16T09:00:00-05:00',
    endTime: '2025-09-16T10:00:00-05:00',
    points: 10,
    description: 'Pick up your badge, meet the R|P team, and get ready for the week ahead.',
    isVirtual: false,
    imageUrl: '',
    location: 'Siebel Center Atrium',
    isVisible: true,
    attendanceCount: 0,
    eventType: 'CHECKIN',
  },
  {
    eventId: 'temporary-2025-opening-ceremony',
    name: 'Opening Ceremony',
    startTime: '2025-09-16T17:00:00-05:00',
    endTime: '2025-09-16T18:00:00-05:00',
    points: 10,
    description: 'Kick off R|P with a welcome from the team and a look at the week ahead.',
    isVirtual: false,
    imageUrl: '',
    location: 'Siebel Center Auditorium',
    isVisible: true,
    attendanceCount: 0,
    eventType: 'SPECIAL',
  },
  {
    eventId: 'temporary-2025-ai-products-talk',
    name: 'Building Delightful AI Products',
    startTime: '2025-09-17T10:00:00-05:00',
    endTime: '2025-09-17T11:00:00-05:00',
    points: 20,
    description:
      'A practical conversation about turning emerging AI capabilities into useful, trustworthy products.',
    isVirtual: false,
    imageUrl: '',
    location: 'Siebel Center 1404',
    isVisible: true,
    attendanceCount: 0,
    eventType: 'SPEAKER',
  },
  {
    eventId: 'temporary-2025-career-fair',
    name: 'Tech Career Fair',
    startTime: '2025-09-18T13:00:00-05:00',
    endTime: '2025-09-18T16:00:00-05:00',
    points: 15,
    description:
      'Meet engineers and recruiters, learn about their teams, and explore internship and full-time opportunities.',
    isVirtual: false,
    imageUrl: '',
    location: 'Siebel Center Atrium',
    isVisible: true,
    attendanceCount: 0,
    eventType: 'CORPORATE',
  },
  {
    eventId: 'temporary-2025-open-source-workshop',
    name: 'Open Source Workshop',
    startTime: '2025-09-19T14:00:00-05:00',
    endTime: '2025-09-19T15:30:00-05:00',
    points: 20,
    description:
      'Learn the contributor workflow by finding an issue, making a focused change, and opening your first pull request.',
    isVirtual: false,
    imageUrl: '',
    location: 'Siebel Center 1302',
    isVisible: true,
    attendanceCount: 0,
    eventType: 'PARTNERS',
  },
  {
    eventId: 'temporary-2025-closing-ceremony',
    name: 'Closing Ceremony',
    startTime: '2025-09-20T16:00:00-05:00',
    endTime: '2025-09-20T17:00:00-05:00',
    points: 10,
    description: 'Celebrate the week and send off R|P together.',
    isVirtual: false,
    imageUrl: '',
    location: 'Siebel Center Auditorium',
    isVisible: true,
    attendanceCount: 0,
    eventType: 'SPECIAL',
  },
];
